# <font color=green> PYTHON PARA DATA SCIENCE - NUMPY
---

# <font color=green> NUMPY BÁSICO
---

Numpy es la abreviatura de Python numérico y es una de las librería más importantes para el procesamiento numérico en Python. Numpy proporciona la base para la mayoría de las libreríaa de aplicaciones científicas que usan datos numéricos en Python (estructuras de datos y algoritmos). Es posible resaltar las siguientes características que contiene la librería Numpy:

- Un poderoso objeto de matriz multidimensional;
- Funciones matemáticas sofisticadas para operaciones con matrices sin la necesidad de usar *for* loops;
- Álgebra lineal y características de generación de números aleatorios

Además de sus usos científicos obvios, la librería NumPy también se usa ampliamente en el análisis de datos como un contenedor multidimensional eficiente de datos genéricos para transporte entre varios algoritmos y librerías en Python.

**Instalación:** https://scipy.org/install.html

**Documentación:** https://numpy.org/doc

### Librerías

Existen varias librerías de Python disponibles para descargar en Internet. Cada librería tiene como objetivo resolver un cierto tipo de problema y para ello se desarrollan nuevos tipos, funciones y métodos.

Algunas librería se usan ampliamente en un contexto de ciencia de datos como:

- Numpy
- Pandas
- Scikit-learn
- Matplotlib

Algunas librería no son distribuídas con la instalación default de Python. En este caso debemos instalar las librería que necesitamos en nuestro sistema para poder utilizar sus funcionalidades.

### Importando toda la librería

In [1]:
import numpy as np

https://numpy.org/doc/1.16/reference/generated/numpy.arange.html

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importando toda la librería y asignadole un alias

In [3]:
import numpy as np

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importando parte de la librería

In [5]:
from numpy import arange

In [6]:
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 5.1 Creando arrays Numpy

In [7]:
import numpy as np

### A partir de listas

https://numpy.org/doc/1.16/user/basics.creation.html

In [8]:
Km = np.array([100, 2300 ,2500])

In [9]:
type(Km)

numpy.ndarray

In [10]:
Km.dtype

dtype('int64')

https://numpy.org/doc/1.16/user/basics.types.html

### A partir de datos externos

https://numpy.org/doc/1.16/reference/generated/numpy.loadtxt.html

In [11]:
Km = np.loadtxt('data/carros-km.txt', dtype= int)

In [12]:
Km

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

In [13]:
Km.dtype

dtype('int64')

### Arrays con dos dimensiones

In [14]:
datos = [ 
    ['Llantas de aleación', 'Cerraduras elétricas', 'Piloto automático', 'Asientos de cuero', 'Aire acondicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de lluvia'],
    ['Central multimídia', 'Techo panorâmico', 'Frenos ABS', '4 X 4', 'Panel digital', 'Piloto automático', 'Asientos de cuero', 'Cámara de estacionamiento'],
    ['Piloto automático', 'Control de estabilidad', 'Sensor crepuscular', 'Frenos ABS', 'Cambio automático', 'Asientos de cuero', 'Central multimídia', 'Vidros eléctricos']
]
datos

[['Llantas de aleación',
  'Cerraduras elétricas',
  'Piloto automático',
  'Asientos de cuero',
  'Aire acondicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de lluvia'],
 ['Central multimídia',
  'Techo panorâmico',
  'Frenos ABS',
  '4 X 4',
  'Panel digital',
  'Piloto automático',
  'Asientos de cuero',
  'Cámara de estacionamiento'],
 ['Piloto automático',
  'Control de estabilidad',
  'Sensor crepuscular',
  'Frenos ABS',
  'Cambio automático',
  'Asientos de cuero',
  'Central multimídia',
  'Vidros eléctricos']]

In [15]:
Accesorios = np.array(datos)

In [16]:
Accesorios

array([['Llantas de aleación', 'Cerraduras elétricas',
        'Piloto automático', 'Asientos de cuero', 'Aire acondicionado',
        'Sensor de estacionamento', 'Sensor crepuscular',
        'Sensor de lluvia'],
       ['Central multimídia', 'Techo panorâmico', 'Frenos ABS', '4 X 4',
        'Panel digital', 'Piloto automático', 'Asientos de cuero',
        'Cámara de estacionamiento'],
       ['Piloto automático', 'Control de estabilidad',
        'Sensor crepuscular', 'Frenos ABS', 'Cambio automático',
        'Asientos de cuero', 'Central multimídia', 'Vidros eléctricos']],
      dtype='<U25')

In [17]:
Km.shape

(258,)

In [18]:
Accesorios.shape

(3, 8)

### Comparando el desempeño con listas

In [19]:
np_array = np.arange(1000000)

In [20]:
py_list = list(range(1000000))

In [21]:
%time for _ in range(100): np_array *= 2

CPU times: user 49.5 ms, sys: 1.26 ms, total: 50.7 ms
Wall time: 49.5 ms


In [22]:
%time for _ in range(100): py_list = [x * 2 for x in py_list]

CPU times: user 8.59 s, sys: 1.87 s, total: 10.5 s
Wall time: 10.5 s


# 5.2 Operaciones aritméticas con arrays Numpy

### Operaciones entre arrays y constantes

In [23]:
km = [44410., 5712., 37123., 0., 25757.]
anhos = [2003, 1991, 1990, 2019, 2006]

In [24]:
edades = []
for anho in anhos:
    edades.append(2019 - anho)
edades

[16, 28, 29, 0, 13]

In [25]:
km = np.array([44410., 5712., 37123., 0., 25757.])
anhos = np.array([2003, 1991, 1990, 2019, 2006])

In [26]:
edad = 2019 - anhos
edad

array([16, 28, 29,  0, 13])

In [27]:
Km

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

### Operaciones entre arrays

In [28]:
Km_media = km / edad

<ipython-input-28-2a3bbee0f7f0>:1: RuntimeWarning: invalid value encountered in true_divide
  Km_media = km / edad


In [29]:
Km_media

array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

In [30]:
44410 / (2019 - 2003)

2775.625

### Operaciones con arrays de dos dimensiones

In [31]:
datos = np.array([km, anhos])
datos

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [32]:
datos.shape

(2, 5)

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [33]:
datos[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [34]:
datos[1]

array([2003., 1991., 1990., 2019., 2006.])

In [35]:
km_medio_datos = datos[0] / (2019 - datos[1])
km_medio_datos

<ipython-input-35-bc06ce656048>:1: RuntimeWarning: invalid value encountered in true_divide
  km_medio_datos = datos[0] / (2019 - datos[1])


array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

# 5.3 Selecciones con arrays Numpy

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

![1410-img02.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img02.png)

### Indexación 

<font color=red>**Observación:**</font> La indexación tiene origen en cero.

In [36]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
contador[1]

1

In [38]:
contador[-1]

9

In [39]:
datos[0]

array([44410.,  5712., 37123.,     0., 25757.])

## <font color=green>**Consejos:**</font>
### *ndarray[ línea ][ columna ]* o *ndarray[ línea, columna ]*

In [ ]:
datos[1][2]

In [ ]:
datos[1,2]

 ### Rebanar
 
La sintaxis para realizar el rebanado en un array Numpy es $i : j : k$ donde $i$ es el índice inicial, $j$ es el índice de parada, y $k$ es el indicador de paso ($k\neq0$)
 
<font color=red>**Observación:**</font> En las rebanadas (*slices*) el item con índice i es **incluído** y el item con índice j **no es incluído** en el resultado.

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [ ]:
contador_ = np.arange(10)
contador_

In [ ]:
contador_[1:4]

In [ ]:
contador_[1:8:2]

In [ ]:
contador_[0:9:2]

In [ ]:
contador_[::2]

In [ ]:
contador_[1::2]

In [ ]:
datos[:, 1:4]

In [ ]:
datos[:, 1:3][0] / (2019 - datos[:, 1:3][1])

In [ ]:
datos[:, 1:4][1]

In [ ]:
datos[0] / (2019 - datos[1])

### Indexación con array booleano

<font color=red>**Observación:**</font> Selecciona un grupo de líneas y columnas según los rótulos o un array booleano.

In [40]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
contador > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [42]:
contador[contador > 5]

array([6, 7, 8, 9])

In [43]:
contador[[False, False, False, False, False, False,  True,  True,  True,
        True]]

array([6, 7, 8, 9])

In [44]:
datos

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [45]:
datos[1] > 2000

array([ True, False, False,  True,  True])

In [46]:
datos[:, datos[1] > 2000]

array([[44410.,     0., 25757.],
       [ 2003.,  2019.,  2006.]])

In [47]:
datos_test = np.array(
    [
        ['Roberto', 'casado', 'masculino'],
        ['Sheila', 'solteiro', 'femenino'],
        ['Bruno', 'solteiro', 'masculino'],
        ['Rita', 'casado', 'femenino']
    ]
)

In [48]:
datos_test[0::2, :2]

array([['Roberto', 'casado'],
       ['Bruno', 'solteiro']], dtype='<U9')

In [49]:
datos_test[0:2, datos_test[2] == 'masculino']
datos_test

array([['Roberto', 'casado', 'masculino'],
       ['Sheila', 'solteiro', 'femenino'],
       ['Bruno', 'solteiro', 'masculino'],
       ['Rita', 'casado', 'femenino']], dtype='<U9')

In [50]:
datos_test.shape

(4, 3)

# 5.4 Atributos y métodos de arrays Numpy

### Atributos

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-attributes

In [51]:
datos.shape

(2, 5)

## *ndarray.shape*

Retorna una tupla con las dimensiones del array.

In [ ]:
datos.shape

## *ndarray.ndim*

Retorna el número de dimensiones del array.

In [ ]:
datos.ndim

## *ndarray.size*

Retorna el número de elementos del array.

In [ ]:
datos.size

## *ndarray.dtype*

Retorna el tipo de datos de los elementos del array.

In [ ]:
datos.dtype

## *ndarray.T*

Retorna el array transpuesto, esto es, convierte líneas en columnas y vice-versa.

In [ ]:
datos.T

In [ ]:
datos.transpose()

### Métodos

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-methods

## *ndarray.tolist()*

Retorna el array como una lista Python.

In [ ]:
datos.tolist()

## *ndarray.reshape(shape[, order])*

Retorna un array que contiene los mismos datos con una nueva forma.

In [52]:
contador_t = np.arange(10)
contador_t

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
contador_t.reshape((5 ,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [56]:
contador_t.reshape((5 ,2), order='C')

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [55]:
contador_t.reshape((5,2), order='F')

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [ ]:
km = [44410, 5712, 37123, 0, 25757]
anhos = [2003, 1991, 1990, 2019, 2006]

In [ ]:
km = [44410, 5712, 37123, 0, 25757]
anhos = [2003, 1991, 1990, 2019, 2006]

In [ ]:
info_autos = km + anhos
info_autos

In [ ]:
np.array(info_autos).reshape((2,5))

In [ ]:
np.array(info_autos).reshape((5,2), order='F')

## *ndarray.resize(new_shape[, refcheck])*

Altera la forma y el tamaño del array.

In [ ]:
datos_new = datos.copy()
datos_new

In [ ]:
datos_new.resize((3,5) ,refcheck=False)

In [ ]:
datos_new

In [ ]:
datos_new[2] = datos_new[0] / (2019 - datos_new[1])

In [ ]:
datos_new

# 5.5 Estadísticas con arrays Numpy

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#calculation

y

https://numpy.org/doc/1.16/reference/routines.statistics.html

y

https://numpy.org/doc/1.16/reference/routines.math.html

In [ ]:
anhos = np.loadtxt(fname = "data/carros-anos.txt", dtype = int)
km = np.loadtxt(fname = "data/carros-km.txt")
valor = np.loadtxt(fname = "data/carros-valor.txt")

In [ ]:
anhos.shape

https://numpy.org/doc/1.16/reference/generated/numpy.column_stack.html

In [ ]:
dataset = np.column_stack((anhos, km, valor))
dataset

In [ ]:
dataset.shape

## *np.mean()*

Retorna la média de los elementos del array a lo largo del eje especificado.

In [ ]:
np.mean(dataset, axis = 0)

In [ ]:
np.mean(dataset[:, 1])

In [ ]:
np.mean(dataset[:, 2])

## *np.std()*

Retorna el desvío padrón de los elementos del array a lo largo del eje especificado.

In [ ]:
np.std(dataset[:, 2])

## *ndarray.sum()*

Retorna la suma de los elementos del array a lo largo del eje especificado.

In [ ]:
np.sum(dataset[:,1])

In [ ]:
dataset.sum(axis= 0)

In [ ]:
dataset[:, 1].sum()

## *np.sum()*

Retorna la suma de los elementos del array a lo largo del eje especificado.

In [ ]:
np.sum(dataset, axis=0)

In [ ]:
np.sum(dataset[:, 2])

In [ ]:
edades = np.array([10, 23, 45, 34, 25])

In [ ]:
np.sum(edades) / edades.size

In [ ]:
np.mean(edades)

In [ ]:
edades.mean()